FROM golang:1.21-alpine AS builder

WORKDIR /app

# Копируем только файлы, необходимые для получения зависимостей
COPY go.mod go.sum ./
RUN go mod download

# Копируем остальные файлы
COPY . .

# Собираем приложение
RUN CGO_ENABLED=0 GOOS=linux go build -o /go/bin/agent ./cmd/agent

# Финальный образ
FROM alpine:3.17

# Устанавливаем сертификаты
RUN apk --no-cache add ca-certificates

# Копируем бинарный файл из builder образа
COPY --from=builder /go/bin/agent /usr/local/bin/agent

# Запускаем приложение
ENTRYPOINT ["agent"]